### ISSUE TITLE
JdbcSinkConnector discussion

### ISSUE THREAD

**Issue by a-panchenko** [openconnectors/connectors#27]
In `SinkConnector` method `publish` accepts a collection of some messages. In case of `JdbcSinkConnector` it will be a collection of `Record`s, where each `Record` is supposed to be converted to row in a database. Is it supposed to publish a collection of `Record`s that belong to different databases or one instance of `JdbcSinkConnector` is supposed to be used only for one table in a database?

**Comment by srkukarni** [comment]
IMO one instance currently should only deal with one table in a database.
